create table if not exists members (
  id bigint primary key,
  name text not null unique,
  can_drive boolean not null default false,
  active boolean not null default true
);

create table if not exists venues (
  id bigint primary key,
  name text not null unique,
  capacity integer not null default 3
);

create table if not exists months (
  id bigint primary key,
  year integer not null,
  month integer not null,
  survey_status text not null default 'draft',
  survey_deadline text,
  schedule_published boolean not null default false,
  unique(year, month)
);

create table if not exists survey_dates (
  id bigint primary key,
  month_id bigint not null references months(id) on delete cascade,
  date text not null,
  unique(month_id, date)
);

create table if not exists responses (
  id bigint generated by default as identity primary key,
  month_id bigint not null references months(id) on delete cascade,
  member_id bigint not null references members(id) on delete cascade,
  updated_at timestamptz not null default now(),
  unique(month_id, member_id)
);

create table if not exists response_days (
  response_id bigint not null references responses(id) on delete cascade,
  date text not null,
  availability text not null check(availability in ('ok', 'maybe', 'ng')),
  primary key(response_id, date)
);

create table if not exists assignments (
  id bigint generated by default as identity primary key,
  month_id bigint not null references months(id) on delete cascade,
  date text not null,
  venue_id bigint not null references venues(id) on delete cascade,
  slot integer not null,
  member_id bigint references members(id) on delete set null,
  unique(month_id, date, venue_id, slot)
);

alter table members enable row level security;
alter table venues enable row level security;
alter table months enable row level security;
alter table survey_dates enable row level security;
alter table responses enable row level security;
alter table response_days enable row level security;
alter table assignments enable row level security;

create policy "public read members" on members for select using (active = true);
create policy "public read venues" on venues for select using (true);
create policy "public read months" on months for select using (survey_status <> 'draft' or schedule_published = true);
create policy "public read survey dates" on survey_dates for select using (true);
create policy "public read responses" on responses for select using (true);
create policy "public insert responses" on responses for insert with check (true);
create policy "public update responses" on responses for update using (true) with check (true);
create policy "public delete responses" on responses for delete using (true);
create policy "public read response days" on response_days for select using (true);
create policy "public insert response days" on response_days for insert with check (true);
create policy "public delete response days" on response_days for delete using (true);
create policy "public read published assignments" on assignments for select using (true);
